/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaiementsRouteImport } from './routes/paiements'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FumerIndexRouteImport } from './routes/fumer.index'
import { Route as BoireIndexRouteImport } from './routes/boire.index'
import { Route as FumerAromeRouteImport } from './routes/fumer.$arome'
import { Route as BoireCategoryRouteImport } from './routes/boire.$category'

const PaiementsRoute = PaiementsRouteImport.update({
  id: '/paiements',
  path: '/paiements',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FumerIndexRoute = FumerIndexRouteImport.update({
  id: '/fumer/',
  path: '/fumer/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoireIndexRoute = BoireIndexRouteImport.update({
  id: '/boire/',
  path: '/boire/',
  getParentRoute: () => rootRouteImport,
} as any)
const FumerAromeRoute = FumerAromeRouteImport.update({
  id: '/fumer/$arome',
  path: '/fumer/$arome',
  getParentRoute: () => rootRouteImport,
} as any)
const BoireCategoryRoute = BoireCategoryRouteImport.update({
  id: '/boire/$category',
  path: '/boire/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evenements': typeof EvenementsRoute
  '/paiements': typeof PaiementsRoute
  '/boire/$category': typeof BoireCategoryRoute
  '/fumer/$arome': typeof FumerAromeRoute
  '/boire/': typeof BoireIndexRoute
  '/fumer/': typeof FumerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evenements': typeof EvenementsRoute
  '/paiements': typeof PaiementsRoute
  '/boire/$category': typeof BoireCategoryRoute
  '/fumer/$arome': typeof FumerAromeRoute
  '/boire': typeof BoireIndexRoute
  '/fumer': typeof FumerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evenements': typeof EvenementsRoute
  '/paiements': typeof PaiementsRoute
  '/boire/$category': typeof BoireCategoryRoute
  '/fumer/$arome': typeof FumerAromeRoute
  '/boire/': typeof BoireIndexRoute
  '/fumer/': typeof FumerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evenements'
    | '/paiements'
    | '/boire/$category'
    | '/fumer/$arome'
    | '/boire/'
    | '/fumer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evenements'
    | '/paiements'
    | '/boire/$category'
    | '/fumer/$arome'
    | '/boire'
    | '/fumer'
  id:
    | '__root__'
    | '/'
    | '/evenements'
    | '/paiements'
    | '/boire/$category'
    | '/fumer/$arome'
    | '/boire/'
    | '/fumer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvenementsRoute: typeof EvenementsRoute
  PaiementsRoute: typeof PaiementsRoute
  BoireCategoryRoute: typeof BoireCategoryRoute
  FumerAromeRoute: typeof FumerAromeRoute
  BoireIndexRoute: typeof BoireIndexRoute
  FumerIndexRoute: typeof FumerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/paiements': {
      id: '/paiements'
      path: '/paiements'
      fullPath: '/paiements'
      preLoaderRoute: typeof PaiementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fumer/': {
      id: '/fumer/'
      path: '/fumer'
      fullPath: '/fumer/'
      preLoaderRoute: typeof FumerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boire/': {
      id: '/boire/'
      path: '/boire'
      fullPath: '/boire/'
      preLoaderRoute: typeof BoireIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fumer/$arome': {
      id: '/fumer/$arome'
      path: '/fumer/$arome'
      fullPath: '/fumer/$arome'
      preLoaderRoute: typeof FumerAromeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boire/$category': {
      id: '/boire/$category'
      path: '/boire/$category'
      fullPath: '/boire/$category'
      preLoaderRoute: typeof BoireCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvenementsRoute: EvenementsRoute,
  PaiementsRoute: PaiementsRoute,
  BoireCategoryRoute: BoireCategoryRoute,
  FumerAromeRoute: FumerAromeRoute,
  BoireIndexRoute: BoireIndexRoute,
  FumerIndexRoute: FumerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
